### ISSUE TITLE
3D Viewer controls (layer/download/dev stage) implementation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#107]
- Layers button and submenu to add strata objs to the scene (pharynx, nerve ring, worm body) (3)
- Download button: Download all objs (5)
   - we zip all the objs in the scene and we download them.
   - we will have gltf, to check if this is fine with the client. (for Dario).
- Download button: Generate a screenshot (5)
   - to investigate, mvg is already doing something similar, to check with Afonso.
   - this estimate accounts for backend and frontend.
- Dev stage button and card with component implementation to let the user change the dev stage displayed from a viewer. (12h, estimate allocated in #44)
  - for each instance we will fetch all the instances in the new specified time point.
  - if an instance does not exists it will not be displayed
  - warning message for the above will have to be discussed and will be addressed with a separate card.
  - this point account for the frontend implementation
  - the rest of the implementation has been scheduled for the #44
- Color picker component to be plugged to the set color of instances and groups

**Comment by afonsobspinto** [comment]
https://github.com/bubkoo/html-to-image
