### ISSUE TITLE
Create dropbox app and token for metacell

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#112]
From this link https://www.dropbox.com/developers/apps/create :

1. create an app
2. set permission to app folder and set this to the folder will contain all the datasets
3. name your app, not really any preference in this sense, "neuroscan-promoterdb" would work but if you prefer anything else it's fine for us, just let us know what the name will be. 
4. click the button "create" in the bottom-right corner

Once clicked you will be redirected to another page, similar to the screenshot below here
![screenshot (15).png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/ac7139db-083e-4239-9a4d-c5fddcee1330)

From this view, scroll down a little bit and:
1. from "App secret" click show
2. from access token expiration dropdown select "no expiration", this will be temporary just for development, then we can define a strategy to have short-lived tokens in the future.
3. from "generate access token" click the button generate
4. forward to us via email the api key, api secret and the generated token or take a screenshot that show all and attach that in an email.

Thanks!

**Comment by lrebscher** [comment]
We need to allow the App to read and write files, this can be set in the permissions folder as shown below:

<img width="1197" alt="Bildschirmfoto 2021-07-07 um 09 56 28" src="https://user-images.githubusercontent.com/7281685/124721730-a6bc7380-df09-11eb-8016-484099139f96.png">

<img width="1123" alt="Bildschirmfoto 2021-07-07 um 09 56 34" src="https://user-images.githubusercontent.com/7281685/124721744-a9b76400-df09-11eb-85f7-968890be0100.png">

**Comment by zsinnema** [comment]
@ddelpiano it seems that the token is expired or invalid. 
also it's missing the `file_requests.read` permission

can you ask for a new, non expiring, token
