### ISSUE TITLE
Data questions

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#121]
**Contacts:**

a) If it's true that we can have multiple Pre->Post contacts we need a new unique identifier for contacts.

Comments from the call: this would be for synapses

**Synapses:**

b) What's the difference between the following files:

SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_yellow-1.obj

SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_plum-0.obj

**Comment by afonsobspinto** [comment]
Context for b):
@afonsobspinto @dario just checked my inferred assumption about duplicated objs in the data & my assumption was wrong.
Objs between
AIBR_PostSyn & ADAL_PreSyn are different (in terms of content)
AVER_PostSyn and AIBR_PostSyn are duplicated (for dyadic & triadic neurons)

Examples:
AIBR_PostSyn
SketchVolumeViewer_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000postSyn_royal-0
ADAL_PreSyn
SketchVolumeViewer_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-0
SketchVolumeViewer_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-1
SketchVolumeViewer_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-2
AVER_PostSyn
SketchVolumeViewer_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000postSyn_royal-1
