### ISSUE TITLE
Assign color to 3d instances according to universal legend

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#163]
This is an extra card, please check with the pm or the tech lead for hours availability before to work on this.

Color legend:
https://drive.google.com/file/d/1_C0M3DtNi1oE-71vng9--dDsWBMzS8uL/view?usp=sharing

**Comment by ddelpiano** [comment]
@zsinnema moving this to the sprint backlog since I got news that this should happen this month as part of the hosting hours that yale is paying for.
Please sync with Stephen and Paolo if you have any question about it (I will be off 8-22 of this month).

**Comment by zsinnema** [comment]
deployed on dev: https://www.neuroscan.dev.metacell.us/
