### ISSUE TITLE
Ingest new data provided

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#179]

**Comment by ddelpiano** [comment]
@zsinnema 

```
Due to the space issue on dropbox, I only have three datasets available: 
1. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L1\SEM_L1_3_0
2. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\Adult\N2U
3.E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L4\JSH
```

**Comment by ddelpiano** [comment]
@zsinnema latest update from yale

- Synapse Adult/48/synapses/SVV_SAAVRelectricalAVAR-A.gltf missing pre/post information. 
**We can remove the electrical synapses**

- The previous convention given (SVV_ADFRundefinedAIZR&AUAR~A__1_1_00001postSyn.obj) has now changed in SVV_RIFRchemicalAWBR_HSNL-A_post1.gltf
**The counter starts always from 1**


- We found some files like this, SVV_ASHLchemicalDROP-unk_AVBL_ADLL-A_post2
**We can ingest the DROP-unk synapses, they are aware these are not linked to neurons.**

The spreadsheet https://docs.google.com/spreadsheets/d/1xebylc--TuJbYXXj6znuUzhmjcNyYt0B/edit#gid=1075431459 has been updated with the newest information.

**Comment by zsinnema** [comment]
@ddelpiano see below
 
```
Due to the space issue on dropbox, I only have three datasets available: 
1. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L1\SEM_L1_3_0
ZS: this one is not on the dropbox folder (btw the naming of the folders should be the timepoint in minutes!!! SEM_L1_3_0 is not according to this)

> 2. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\Adult\N2U
ZS: This one I've already ingested

> 3.E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L4\JSH
ZS: This one I've also already ingested (2160 minutes or 36 hours)
```

**Comment by zsinnema** [comment]
> @zsinnema latest update from yale
> 
> * Synapse Adult/48/synapses/SVV_SAAVRelectricalAVAR-A.gltf missing pre/post information.
>   **We can remove the electrical synapses**
ZS: I changed the ingestion to skip "incorrect" formatted files meaning that this one will be skipped

> * The previous convention given (SVV_ADFRundefinedAIZR&AUAR~A__1_1_00001postSyn.obj) has now changed in SVV_RIFRchemicalAWBR_HSNL-A_post1.gltf
>   **The counter starts always from 1**
ZS: clear this is how I already implemented it

> * We found some files like this, SVV_ASHLchemicalDROP-unk_AVBL_ADLL-A_post2
>   **We can ingest the DROP-unk synapses, they are aware these are not linked to neurons.**
ZS: I've also implemented it like this

> 
> The spreadsheet https://docs.google.com/spreadsheets/d/1xebylc--TuJbYXXj6znuUzhmjcNyYt0B/edit#gid=1075431459 has been updated with the newest information.
ZS: I've changed the "production"/"staging" database according to this

**Comment by ddelpiano** [comment]
> @ddelpiano see below
> 
> ```
> Due to the space issue on dropbox, I only have three datasets available: 
> 1. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L1\SEM_L1_3_0
> ZS: this one is not on the dropbox folder (btw the naming of the folders should be the timepoint in minutes!!! SEM_L1_3_0 is not according to this)
> 
> > 2. E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\Adult\N2U
> ZS: This one I've already ingested
> 
> > 3.E:\Colon Ramos Lab Dropbox\Colon Ramos Lab Dropbox\WormGUIDES DCR\Apps\DCR-PromoterDB\MetaCell structure\NeuroSCAN\L4\JSH
> ZS: This one I've also already ingested (2160 minutes or 36 hours)
> ```

@zsinnema I am reviewing the datasets myself, will sync with yale once I finish the download and I can see which one is complete and which one isn't. Thanks
