### ISSUE TITLE
PromoterDB Header should be scrollable

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#218]
Right now half of the UI in promoter db is locked on the header and there is less than half screen for the content.

The header should scroll with the rest, when scrolling the search should scroll as well up to the top where the search should be stick if the user continue to scroll.

**Comment by vidhya-metacell** [comment]
Keeping the header visible, search box would be scrollable and be sticky under the header, image would hide. @ddelpiano
