### ISSUE TITLE
add other cells without checkmark to promoter card

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#252]
@vidhya-metacell I am assigning this  to you but you don't have the data yet to work on this.

Zoran will ping you with all the information you need to work on this. Thx

**Comment by zsinnema** [comment]
@vidhya-metacell the data is uploaded

**Comment by vidhya-metacell** [comment]
@zsinnema how do i differentiate between cells that need to be with and without checkmark?

**Comment by zsinnema** [comment]
@vidhya-metacell the cells in the field `CellsByLineaging` are with the cells in field `OtherCells` are without

**Comment by vidhya-metacell** [comment]
@zsinnema thank you
