### ISSUE TITLE
3d viewer timepoint slider retaining old instances in the viewer when changing time point

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#266]

**Comment by zsinnema** [comment]
@ddelpiano I've checked it and I think it's a geppetto meta issue. After switching the dev stage the state shows one instance in the widget, that seems to be right to me. It feels like geppetto meta isn't cleaning the scene...

**Comment by ddelpiano** [comment]
I am looking into this.

**Comment by ddelpiano** [comment]
fixed in geppetto
