### ISSUE TITLE
Search / synapses filters broken

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#281]
as per title, not much to add, just try to search for 2 neurons and use the synapses filters

**Comment by ddelpiano** [comment]
@zsinnema this is still a valid issue, tested in the deployment.
Search for AIBR and ADAL, open the search filter, select AIBR as pre.
You will notice that the search will hang with the spinner indefinitely.
Thx

**Comment by zsinnema** [comment]
@ddelpiano I've tested it with branch feature 281 and I get results, and no js error

**Comment by zsinnema** [comment]
@ddelpiano this is the PR: https://github.com/MetaCell/geppetto-NeuroSCAN/pull/286

**Comment by mohler** [comment]
Hi guys-

Bill Mohler here.  I built all the models in NeuroSCAN.  And the code for
CytoSHOW which creates and displays them in Java.

Regarding synapses, the nomenclature was designed specifically so simple
regex searches could pull out whichever relavent synapses a user desires.
Sounds to me like you guys may be using a more indirect route. I would be
happy to consult/advise/learn on this or any other topic...

Bill Mohler
UConn Health
WormGUIDES.org
Collaborator with Daniel and Noelle at Yale.
