### ISSUE TITLE
Synchronise feature

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#32]
Scope:

- implementation of the button in the morphology viewer
- implement logic to handle all the cameras together across different morphology viewers.

@lrebscher I increased the estimate from the user stories by 8 hours to address inside this card also the button + menu implementation, plus whatever additional logic is required for the synchronisation but this is just a rough estimate so feel free to change this number.

**Comment by lrebscher** [comment]
estimate is fine for me

**Comment by ddelpiano** [comment]
modified during the call with Noelle and the team.
Scope of the implementation, have a single button to trigger the 360 rotation of all the morphology viewers on focus on neuroscan.
