### ISSUE TITLE
Inspector component skeleton

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#55]
This card should address:
- component styling
- Top level path in the component to show the tree path of the component visualised in the inspector
- Depending on the type of the instance shown by the inspector, we will have to show different components, such as

  - Input text to change the name of the instance
  - read only input text for structures (neurons, synapses and contacts).
  - color picker to change color and transparency
  - button to hide/show the structure
  - download button (functionalities can differ depending on the type of instance shown, for structures we download the objs, for viewers we download svg/png images).
  - Text section to show whatever metadata the instance has available.
  - for neurons, we list the connections relevant to the neuron shown in the inspector.
  - for the viewers (morphology or cphate) we show the developmental stage slider
  - Only for the morphology viewers the strata section with buttons to add the worm body, pharynx and/or the nerve ring.
  - List of neurons when a cluster of the cphate is selected.

**Comment by lrebscher** [comment]
@ddelpiano  the developmental stage slider is here read-only, right?
