### ISSUE TITLE
Tree explorer skeleton

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#58]
This card should address:

- component styling
- create the tree structure of all the instances loaded in the scene (examples in the mockups)
- 3dots button to open a submenu/popup based
- submenu choices based on the instance type

**Comment by lrebscher** [comment]
@ddelpiano let's have a chat about the search results display, not sure I understand what is shown in the mockups

**Comment by ddelpiano** [comment]
@vidhya-metacell the input text has been removed from the list since it's not part of the mvp.
Thx

**Comment by ddelpiano** [comment]
@lrebscher estimate and description revisited to split frontend development from the component sync with the redux store as discussed for the sprint, feel free to adjust the estimate and the description if you prefer otherwise.
