### ISSUE TITLE
Record feature implementation

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#60]

**Comment by lrebscher** [comment]
**Record**
- Record & stop buttons
- Capture Canvas scene either by using third-party library such as [threecap](https://github.com/jbaicoianu/threecap) or by using [Media Library](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder)
- Popup + Image preview + Download button

**Auto-rotate**
- Play button + action (auto-rotate)
- Button to trigger play for all viewers

**Comment by afonsobspinto** [comment]
https://github.com/spite/ccapture.js/ looks interesting.
threecap requires recording time beforehand and that's a negative point.
More notes:
https://stackoverflow.com/questions/50681683/how-to-save-canvas-animation-as-gif-or-webm
