### ISSUE TITLE
Parser for data ingestion

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#78]
Schema: https://docs.google.com/spreadsheets/d/14u31AzaxxYfeeGY63iEEMzuSMq0DHbM2xIgz288AQ5w/edit#gid=0

- Parser for CPHATE data
- Parser for neurons
- Parser for contacts
- Parser for synapses

Yale provided the objs and xlsx files that encodes all the information required for neurons, synapses, contacts, etc.
The parser(s) will have to go through these data in order to fill the xlsx schema file attached, the xlsx will be then used by strapi to populate the db in the ingestion pipeline.

@afonsobspinto added this to ease the transition of this since Zoran will take over the development when you are in holiday:
- write documentation for the parser

**Comment by afonsobspinto** [comment]
Some neuron obj files seem to be repeated:
- SketchVolumeViewer_SMDDR_SMDDR_1_1_0000(1).obj
- SketchVolumeViewer_URADL_URADL_1_1_0000(1).obj
- SketchVolumeViewer_SMDVR_SMDVR_1_1_0000(1).obj
- SketchVolumeViewer_SMDVL_SMDVL_1_1_0000(1).obj
- SketchVolumeViewer_SMDDL_SMDDL_1_1_0000(1).obj

**Comment by afonsobspinto** [comment]
There are many neuron .mtl files that do not have a correspondent .obj file

**Comment by afonsobspinto** [comment]
Synapses parser notes:

Initially, I got the idea that the obj file would refer to only one synapse but apparently, it can refer to many?

Example:
```
'SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_yellow-1.obj'
'SketchVolumeViewer_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_AIBRchemicalDVC_RIBL_AVDR_certainJSHJSH060_zs1_1_1_0000preSyn_plum-0.obj'
```
> what does it mean when we have more than one neuron in 'main' neuron place like in the following:

**Comment by afonsobspinto** [comment]
Apparently no problems with contacts.
Generated csv [here](https://docs.google.com/spreadsheets/d/1YxQPpp9lm1iGX7E4AQwF8K9iVN6-xG9mJO5Set5LArA/edit?usp=sharing)

**Comment by lrebscher** [comment]
**Update about synapses**

* We don't need to do any matching between pre and post synapse folders, they are treated as independent categories
* Synapses are grouped into pairs by their


**Update about mtl files**

mtl files need to be collected as well so that we can upload them to Strapi.
* Neurons have one mtl file per obj file
* Synapses & contacts share one mtl file per folder

**Dropbox folder structure**

We have to wait until the folder structure in dropbox is ready and fixed.

**Comment by afonsobspinto** [comment]
Update about the update about mtl files

It no longer applies because we just need to upload the gltf file now cc @lrebscher

**Comment by lrebscher** [comment]
> Neurons parser notes:
> 
> Some neuron obj files seem to be repeated:
> 
> * SketchVolumeViewer_SMDDR_SMDDR_1_1_0000(1).obj
> * SketchVolumeViewer_URADL_URADL_1_1_0000(1).obj
> * SketchVolumeViewer_SMDVR_SMDVR_1_1_0000(1).obj
> * SketchVolumeViewer_SMDVL_SMDVL_1_1_0000(1).obj
> * SketchVolumeViewer_SMDDL_SMDDL_1_1_0000(1).obj
> 
> There are many neuron .mtl files that do not have a correspondent .obj file
> 
> Since we have multiple sources for neurons, the final result, currently, is the union between all of them (merging on neurons with the same name)
> 
> Generated CSV available [here](https://docs.google.com/spreadsheets/d/1CSk63l3D3D1awgYoMhqPCG0MC4MezPoSQswNIRHYwUU/edit?usp=sharing)

seems to be fixed in Dropbox neurons folder, otherwise we ignore (1) duplicates, a neuron will have only one obj per timepoint

**Comment by lrebscher** [comment]
**Update - Synapses**

We will parse the index at the end of the obj file. For dyadic and triadic synapses, we have one obj per post-synaptic neuron.

Example:

1. SketchVolumeViewer_ADALchemical**AIBR&AVER&RIML**_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-**0**

2. SketchVolumeViewer_ADALchemical**AIBR&AVER&RIML**_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-**1**

3. SketchVolumeViewer_ADALchemical**AIBR&AVER&RIML**_certainJSHJSH234_zs7_ADALchemicalAIBR&AVER&RIML_certainJSHJSH234_zs7_1_1_0000preSyn_yellow-**2**

index 0 -> AIBR
index 1 -> AVER
index 2 -> RIML

**Comment by lrebscher** [comment]
❗  In the Dropbox folder, some Synapse filenames use & instead of \_ to separate post-synaptic neurons.

<img width="812" alt="Bildschirmfoto 2021-07-26 um 19 10 36" src="https://user-images.githubusercontent.com/7281685/127030446-d42899ae-cb35-4ed3-b4b9-4f57395ebccc.png">

**Comment by afonsobspinto** [comment]
Imo can be closed. A new issue should be created to:

- add a minimal setup.py to ingestion folder so that one can install & run this without having to modify sys.path, IntelliJ does this automatically for you but if you run a parser from the CLI it won't be aware of the ingestion module. For that you better add another ingestion folder that will contain the source code, so ingestion/ingestion/parser and ingestion/setup.py

- we need to add some documentation here, a general how to use and also code documentation, e.g. of the pipeline syntax and filename config

cc @ddelpiano

**Comment by ddelpiano** [comment]
@zsinnema 
- are you ok with the above?
- has the point 1 already been addressed by the refactoring you did for cli?

In case I will open another card for Afonso to work on the documentation.

Thx.

**Comment by zsinnema** [comment]
@afonsobspinto added the setup.py and moved the parser to the folder ingestion

`pip install -e .` will install the ingestion package

**Comment by zsinnema** [comment]
I created a new issue for the documentation here: https://github.com/MetaCell/geppetto-NeuroSCAN/issues/159
