### ISSUE TITLE
Implement connector to dropbox where raw data is located

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#86]

**Comment by ddelpiano** [comment]
moved to icebox since we need to establish if yale can give us direct access to the server where the dataset is stored, in that case the connectore will be developed to ingest the data from their server.

**Comment by lrebscher** [comment]
**Outcome of first analysis:**

*  We can use the official [dropbox JS client](https://github.com/dropbox/dropbox-sdk-js) to download data files & upload them to Strapi when a user imports a CSV by using the UI plugin

* The CSV that is imported will contain file paths that are used to find the paths in the Dropbox folder. Each file will be first downloaded from Dropbox & then uploaded to Strapi

* We need an access token for the client that can be generated by adding a Dropbox App to the  account, a shared link won't suffice

* The access token will be set as a CF variable and added as ENV variable to the Strapi backend

**Comment by lrebscher** [comment]
An attractive alternative to Dropbox JS client would be using [rclone](https://rclone.org/) to mount the data in the docker container as volume.

**Comment by afonsobspinto** [comment]
Waiting for a token with reading permission

**Comment by zsinnema** [comment]
> **Outcome of first analysis:**
> 
> * We can use the official [dropbox JS client](https://github.com/dropbox/dropbox-sdk-js) to download data files & upload them to Strapi when a user imports a CSV by using the UI plugin
> * The CSV that is imported will contain file paths that match the paths in the Dropbox folder. Each file will be first downloaded from Dropbox & then uploaded to Strapi
> * We need an access token for the client that can be generated by adding a Dropbox App to the  account, a shared link won't suffice
> * The access token will be set as a CF variable and added as ENV variable to the Strapi backend

ad bullit 1:
this sounds like very nice solution however it's not an efficient way to do it, on every import download all files. We could implement a certain method to detect if the  local file differs from the dropbox one and only download if different

**Comment by zsinnema** [comment]
> An attractive alternative to Dropbox JS client would be using [rclone](https://rclone.org/) to mount the data in the docker container as volume.

this sounds like a better solution:
after csv upload sync the dropbox folder with the local folder

**Comment by zsinnema** [comment]
first step is done: installing rclone on the strapi backend server including script to sync from a dropbox folder
in the repo in the backend/rclone folder is the rclone config where the access token is stored
see PR https://github.com/MetaCell/geppetto-NeuroSCAN/pull/147

**Comment by zsinnema** [comment]
this is implemented via the script rclone-sync.sh in the rclone folder on the server
we can use crontab or another ttrigger to trigger the syncing the dropbox with the the local (server) /opt/storage/files
