### ISSUE TITLE
Generate frontend-client based on openapi specification

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-NeuroSCAN#87]

**Comment by afonsobspinto** [comment]
Original error:
![image](https://user-images.githubusercontent.com/19196034/124616359-ea619f80-de6d-11eb-8f58-05233feb6fed.png)

Problem seems to be:
`o.o.codegen.DefaultCodegen - Unknown type found in the schema: uid`

How to fix it?
1. Import documentaiton.json into apicurio
2. Create a new simple data type -> uid
3. Fix the missing type errors using apicurio UI
4. Download the new configuration/specification file
5. Profit

I think it will be wiser to wait for #80 before doing this, but let me know @lrebscher

**Comment by afonsobspinto** [comment]
Waiting for agreement on the model (#80) so that we just need to do the above once

**Comment by afonsobspinto** [comment]
Other changes to apply
ApiClient.js:
this.defaultHeaders = {}; -> fixes 'Ajax request: Refused to set unsafe header'


Neuron (and probably others):
constructFromObject
            if (data.hasOwnProperty('file')) {
                obj['file'] = data['file']['url']
            }
(Fixes [object object])
![image](https://user-images.githubusercontent.com/19196034/126208706-89c8021f-0a11-43c3-9b44-6a8e27d87438.png)
